### ISSUE TITLE
Improve setOrder method

### ISSUE THREAD

**Issue by adayth** [ADmad/cakephp-sequence#11]
I detected that setOrder method fails hard with protected fields ($_accesible Entity definition). With some validation rules, saving entity will fail. I added this line to overcome this issue, but I'm not sure if this is really safe for all types of models (in my app works OK):
```php
$entities = $table->newEntities($data, ['accessibleFields' => ['*' => true]]);
```
This method could also accept an array of entities, so we don't need to convert our entities to an array of data to use setOrder.

Another suggestion. We can add another method to fix list order numbers (CakeDC List has some method like that) based in passed where conditions. For example, if you have positions 1,2,3,4 and move down 1, the result list will be 0,2,3,4 and I prefer it to be 1,2,3,4. This happen with list upper limit too. Right now I'm using setOrder for this, but I need to get entities, convert to array, pass to setOrder...

I can PR some of this changes if you want.

**Comment by ADmad** [comment]
The method needs to update only the ordering field so only that needs to be set accessible. Also the method could be made to take an array of entities too as input.

**Comment by ADmad** [comment]
Each entity is saved with ['validate' => false](https://github.com/ADmad/cakephp-sequence/blob/master/src/Model/Behavior/SequenceBehavior.php#L285) so don't see how validation could be an issue.

**Comment by adayth** [comment]
Sorry, I didin't remember well my issue. My problem was with application rules, not with validation. I checked the proposed changes and *'checkRules' => false* is used.

**Comment by ADmad** [comment]
Yeah 'checkRules' is what was needed.
