### ISSUE TITLE
Plugin namespace

### ISSUE THREAD

**Issue by bravo-kernel** [ADmad/cakephp-sequence#15]
There seems to be some discrepancy between the `Admad/Sequence` namespace used in the readme and the plain `Sequence` one the plugin is actually using. Which PR do you prefer?

**Comment by ADmad** [comment]
Hmm I don't even remember why this plugin isn't vendor namespaced :stuck_out_tongue: I guess for consistency across my plugins it would be better to add the namespace, so a PR for that would be nice. I'll bump major version after that.

**Comment by bravo-kernel** [comment]
Solved in #16
