### ISSUE TITLE
order by order throw mysql error

### ISSUE THREAD

**Issue by djonatanb** [ADmad/cakephp-sequence#18]
I selected my ordering column to be order and got mysql errors.
when I changed to '`order`' it worked.

**Comment by ADmad** [comment]
`order` is a mysql keyword. So better use another name for you columns (that's by the default name used by behavior is 'position'), or turn off `identifierQuoting` in your db connection config.

**Comment by djonatanb** [comment]
I'm aware of that, it's just that I used your tests as documentation, thought it was in the actual documentation. 
https://github.com/ADmad/cakephp-sequence/blob/master/tests/TestCase/Model/Behavior/SequenceBehaviorTest.php#L39
My mistake twice, but just clarifying

**Comment by ADmad** [comment]
That's to test that using a keyword for column name also works (as long a `identifierQuoting` is enabled), hence the name `KeywordItems` :)
