### ISSUE TITLE
Problem when using MySQL reserved words

### ISSUE THREAD

**Issue by veganista** [ADmad/cakephp-sequence#2]
If you use a reserved word as the `order` field the the generated SQL does not get properly escaped when `quoteIdentifiers` is set to true.

Not sure if this is a bug with Cake or not.

__Example__
````php
$this->addBehavior('Sequence.Sequence', [
    'order' => 'order',
    'start' => 0,
    'scope' => 'course_id'
]);
```
Then the following SQL is created:
 ```sql
UPDATE course_modules SET `order` = (order - 1) WHERE (`order` > :c0 AND `course_id` = :c1)
```
You can see the order is not getting escaped. It's caused by these lines 
```php
$this->_table->query()->newExpr()->add("$orderField + 1")
```

**Comment by veganista** [comment]
Update from the IRC

We are not to expect this to be automatically escaped we're to use IdentifierExpression to do it

**Comment by ADmad** [comment]
Closing as PR i opened.
