### ISSUE TITLE
Problems with virtual fields

### ISSUE THREAD

**Issue by alphageek01** [ADmad/cakephp-sequence#21]
I encountered an problem using virtual fields when editing data:
The method "_getOldValue" adds virtual fields to the $values-array (called in line 175). These are later on passed to the database which results in an error - fields not found...

I created an patch which solves this bug for me.

[avoidVirtualFields.txt](https://github.com/ADmad/cakephp-sequence/files/907717/avoidVirtualFields.txt)

**Comment by ADmad** [comment]
Please provide a test case of example code to reproduce the issue.
