### ISSUE TITLE
Restart sequence

### ISSUE THREAD

**Issue by nedvajz** [ADmad/cakephp-sequence#31]
1) Is there possible to restart sequence   
`13,15,14,16 => 1,3,2,4 `
  
2) Or ideally keep the sequence to always start with start value   
`start, start+1, start+2, ...`

**Comment by ADmad** [comment]
There's already `start` config for your option 2.

**Comment by nedvajz** [comment]
Thank you for your reply!  
  
I have set this to `1` but even though it does not start with 1 in database  
  
![image](https://user-images.githubusercontent.com/1135477/62619529-4be20200-b917-11e9-9f88-9cd1b30c51a9.png)
  
expected is 'blue' 1,2,3 but sequence is 5,15,16 .. well for order query it does work fine, but for my special usecase when I wanna retrieve just 3rd item of the `member_id = 12` it does not work as the 3rd item has value `16`

hope it makes sense?

**Comment by ADmad** [comment]
Starting with a "clean" table the behavior will set number in continuous sequence starting with the value specified for `start`. I don't know how you endup with those values.

**Comment by nedvajz** [comment]
I found workaround for my case. 

Probably not that often issue so you can ignore that. But thank you for you help and for this plugin!
   
```
    /**
     * Method: beforeSave
     *
     * Refresh order to be 1,2,3 .. after save
     *
     * @param Event $event Event
     * @param EntityInterface $entity Entity
     * @param ArrayObject $options Options
     * @return void
     */
    public function afterSaveCommit(Event $event, EntityInterface $entity, \ArrayObject $options)
    {
        if (!empty($entity->member_id)) {
            $sort = $this
                ->find('list', [
                    'keyField' => 'id',
                    'valueField' => 'id'
                ])
                ->where(['member_id' => $entity->member_id])
                ->order(['member_sort' => 'desc'])
            ->toArray();  

            $this->setOrder($sort);
        }
    }

```
