### ISSUE TITLE
Field 'position' doesn't have a default value

### ISSUE THREAD

**Issue by JeanValJeann** [ADmad/cakephp-sequence#32]
Hi,

After using successfuly Behavior on a Table having belongsToMany relation and grouping with 'scope' field, I currently trying to use the Behavior on a Table having hasMnay relation. In this case, I don't have to use 'scope' field, I simply want to handle position of each table's record.

I get an **SQL error** : 

"**Error: SQLSTATE[HY000]: General error: 1364 Field 'position' doesn't have a default value**"
**"INSERT INTO gallerycategories (name, slug) VALUES (:c0, :c1)"**

Of course, 'position' field has any default value in my SQL settings.
I don't need it assuming Behavior handles 'position' property in Entity.

I debugged Entity in beforeSave method within Behavior and Entity's got 'position' property.
So, I assumed the Behavior was working as expecded... Then, I tryed to set a default value to my 'position' field in SQL Database and I figured out that 'position' field wasn't set into SQL Database, but 'position' default value was setting in instead.

This is running me crazy, because I successfuly used this great Behavior once. By my side, I checked all I do without any success. The only one difference that I got between my successful use case and now, is not having use 'scope' Behavior setting.

Have you got some ideas ?

**Comment by ADmad** [comment]
If you added the `position` field to tables after the entity was baked, make sure to update the entity class and set `position` field as accessible.

Besides that I have no idea why the field would be missing in query if you have set the behavior for the table.

**Comment by ADmad** [comment]
Actually the behavior directly sets the entity property, no patching is involved, so field accessibility is not an issue. Only other thing I can think of is table schema cache.

**Comment by JeanValJeann** [comment]
That's Okay. You are right, nothing to do with Entity property, it was table schema cache. Thanks.
