### ISSUE TITLE
contains duplicate method "moveup"

### ISSUE THREAD

**Issue by hanuman1989** [ADmad/cakephp-sequence#34]
I have already used Tree Behavior and if i am going to add Sequence Behavior then coming below error:

`ADmad\Sequence\Model\Behavior\SequenceBehavior contains duplicate method "moveup" which is already provided by "Tree"`

![error](https://user-images.githubusercontent.com/3963974/86515472-b73d9800-be36-11ea-8f23-87cb2df5dcd4.png)

**Comment by ADmad** [comment]
Why are you attaching the sequence behavior to a table using tree behaviour? MPTT are already ordered by the "left" field.
