### ISSUE TITLE
Modifying lists? insertAt(), moveTo()?

### ISSUE THREAD

**Issue by burzum** [ADmad/cakephp-sequence#7]
It looks like this behavior is just supporting generating a list on insert but there is no way to modify the list order or insert at a certain position?

**Comment by ADmad** [comment]
It [does](https://github.com/ADmad/cakephp-sequence/blob/master/tests/TestCase/Model/Behavior/SequenceBehaviorTest.php#L66)

**Comment by burzum** [comment]
Oh, OK, thank you! I've missed that because I haven't seen it in the documentation nor noticed it when I was looking at the behavior code. I was expecting some methods like that, similar to the old CakeDC ListBehavior.

**Comment by ADmad** [comment]
It is mentioned in [docblock](https://github.com/ADmad/cakephp-sequence/blob/master/src/Model/Behavior/SequenceBehavior.php#L42). I am not good with detailed readme/docs :)

**Comment by burzum** [comment]
Who's good with that when doing work for free and not getting paid for the boring part? ;)
